/*CREANDO UN TABLESPACE*/

CREATE TABLESPACE JUNIOR_DEVELOPER DATAFILE 'JUNIOR_DEVELOPER.ORA' SIZE 1M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED;

/*CREANDO UN USUARIO comun EN LA BD QUE TENGA FUNCIONES DE DBA*/
CREATE USER C##WALTER IDENTIFIED BY WRPRO DEFAULT TABLESPACE JUNIOR_DEVELOPER;

/*OTORGANDO PERMISOS DE DBA AL USUARIO RECIÉN CREADO*/
GRANT DBA TO C##WALTER;