/*1.- REALIZAR UNA SELECT PARA VISUALIZAR EL SIGUIENTE RESULTADO. 
EL IMPUESTO ES EL 20% DEL SALARIO.*/

SELECT
    FIRST_NAME               AS NOMBRES,
    SALARY                   AS BRUTO,
    (SALARY*20/100)          AS IMPUESTOS,
    (SALARY-(SALARY*20/100)) AS NETO
FROM
    EMPLOYEES
ORDER BY
    NOMBRES DESC;