/*1.- REALIZAR UNA SELECT PARA VISUALIZAR EL SIGUIENTE RESULTADO. 
EL IMPUESTO ES EL 20% DEL SALARIO.*/

SELECT
    FIRST_NAME               AS NOMBRES,
    SALARY                   AS BRUTO,
    (SALARY*20/100)          AS IMPUESTOS,
    (SALARY-(SALARY*20/100)) AS NETO
FROM
    EMPLOYEES
ORDER BY
    NOMBRES DESC;

/*
2. VISUALIZAR EL SALARIO ANUAL DE CADA EMPLEADO, 
POR 14 PAGAS. 
DEBEMOS VISUALIZAR LAS COLUMNAS COMO NOMBRE, 
SALARIO Y SALARIO ANUAL
*/

SELECT
    E.FIRST_NAME AS NOMBRES,
    E.SALARY     AS SALARIO,
    E.SALARY*14  AS PAGO_14_MESES_TRABAJADOS
FROM
    EMPLOYEES E;