/*USO DE LA TABLA DUAL (DE APOYO, ES DECIR, PARA DUMMIES), CUANDO NECESITAMOS SOLO OBTENER UN RESULTADO DE ALGUNA OPERACIÓN*/
SELECT
    20/10
FROM
    DUAL;

/*FUNCION NVL DE ORACLE:
NVL DE ORACLE

LA FUNCIÓN NVL EN ORACLE NOS PERMITE OBTENER UN VALOR CONCRETO EN VEZ DE NULL COMO RESULTADO.

ESTA FUNCIÓN EVALÚA UNA COLUMNA O EXPRESIÓN DE LA SIGUIENTE MANERA:

SI NO ES NULL, DEVUELVE DICHO VALOR.

SI ES NULL, DEVUELVE EL VALOR ALTERNATIVO QUE LE INDICAMOS.


NVL DE ORACLE

LA FUNCIÓN NVL EN ORACLE NOS PERMITE OBTENER UN VALOR CONCRETO EN VEZ DE NULL COMO RESULTADO.

ESTA FUNCIÓN EVALÚA UNA COLUMNA O EXPRESIÓN DE LA SIGUIENTE MANERA:

SI NO ES NULL, DEVUELVE DICHO VALOR.

SI ES NULL, DEVUELVE EL VALOR ALTERNATIVO QUE LE INDICAMOS.

SINTAXIS

NVL(EXPRESIÓN, RESULTADO_SI_NULL)

EL TIPO DE DATO DEL RESULTADO DE LA «EXPRESIÓN» Y «RESULTADO_SI_NULL» TIENEN QUE SER COMPATIBLES.
*/
SELECT
    FIRST_NAME,
    SALARY,
    NVL(COMMISSION_PCT,
    1)
FROM
    EMPLOYEES;

/*COMISION POR SALARIO (SOLO SON PRUEBAS)*/

SELECT
    FIRST_NAME,
    SALARY,
    COMMISSION_PCT,
    (SALARY*NVL(COMMISSION_PCT,
    1)) AS COMISION
FROM
    EMPLOYEES;

/*CLAUSULA DISTINCT, ELIMINA LOS DUPLICADOS SEGÚN LOS VALORES DE LA COLUMNA*/
SELECT
    FIRST_NAME,
    DEPARTMENT_ID
FROM
    EMPLOYEES;

/*SACAR LOS ID DE DEPARTAMENTOS SIN REPERTIRSE*/
SELECT
    DISTINCT DEPARTMENT_ID
FROM
    EMPLOYEES;

/*HACER UN SELECT DISTINCT DE VARIAS COLUMNAS*/
SELECT
    DISTINCT DEPARTMENT_ID,
    JOB_ID
FROM
    EMPLOYEES;

/****************EJERCICIOS DISTINCT*********************/
/*VISUALIZAR LAS CIUDADES DONDE HAY DEPARTAMENTOS, DE LA TABLA LOCATIONS. NO DEBEN SALIR REPETIDOS*/
SELECT
    DISTINCT CITY
FROM
    LOCATIONS;

/*VISUALIZAR LOS DISTINTOS TIPOS DE JOB_ID POR DEPARTAMENTO DE LA TABLA EMPLOYEES.*/
SELECT
    DISTINCT DEPARTMENT_ID,
    JOB_ID
FROM
    EMPLOYEES;