/*uso de la cláusula where*/

/*saber aquellos empleados que trabajan en el departamento 50*/
SELECT
    *
FROM
    EMPLOYEES
WHERE
    DEPARTMENT_ID=50;

.

/*OPERADORES*/
/*
=
>
<
>=
<=
<>
*/

/*EMPLEADOS QUE NO TRABAJAN EN EL DEPARTAMENTO 50*/
SELECT
    *
FROM
    EMPLOYEES
WHERE
    DEPARTMENT_ID<>50;

/*condiciones con literales (strings)*/
/*seleccionar aquellos usuarios que
    tengan nombre John*/


SELECT
    *
FROM
    EMPLOYEES
WHERE
    FIRST_NAME='John';

/*comparar fechas
las fechas se guardan como numeros julianos
la fecha tiene un número específico*/
/*seleccionar aquellos empleados que entraron Entre
el año 2006 y 2007*/
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    TO_DATE(HIRE_DATE,
    'DD/MM/YYYY') AS FECHA_INGRESO
FROM
    EMPLOYEES
WHERE
    EXTRACT(YEAR FROM HIRE_DATE) BETWEEN 2006
    AND 2007;

/*EJERCICIOS SELECT*/
/*
    AVERIGUA LOS EMPLEADOS QUE 
    TRABAJEN EN EL DEPARTAMENTO 100*/
SELECT
    *
FROM
    EMPLOYEES
WHERE
    DEPARTMENT_ID IN(100);

/*
DE LA CIUDAD (CITY) Y LA DIRECCIÓN (STREET_ADDRESS) DE LOS DEPARTAMENTOS SITUADOS EN ESTADOS UNIDOS COUNTRY_ID=US*/

SELECT
    *
FROM
    LOCATIONS
WHERE
    COUNTRY_ID=US;

/*VISUALIZA LOS PAÍSES QUE ESTÁN EN LA REGIÓN 3
 (REGION_ID DE LA TABLA COUNTRIES*/
SELECT
    DISTINCT COUNTRY_NAME,
    REGION_ID
FROM
    COUNTRIES
WHERE
    REGION_ID=3;

/*AVERIGUAR EL NOMBRE Y

SALARIO DE LOS EMPLEADOS QUE NO TENGAN COMO JEFE AL MANAGER 114 (COLUMNA MANAGER_ID)*/
/*VISUALIZAR LOS EMPLEADOS QUE EMPEZARON A TRABAJAR A PARTIR DEL AÑO 2006 • SELECCIONAR LOS EMPLEADOS QUE TENGA COMO TIPO DE TRABAJO ‘ST_CLERK’ • INDICAR LOS DATOS DE LOS EMPLEADOS QUE TENGAN COMO APELLIDOS “SMITH” (LAST_NAME) */